// app-mobile/src/rich-content/TextArtifactCard.tsx
import { useRef } from 'react';
import { Button } from 'react-aria-components';

import type { NormalizedTextArtifactBlock } from './normalizeTranscriptBlocks.js';
import { RichBlockFrame } from './RichBlockFrame.js';
import { useCopyFeedback } from './useCopyFeedback.js';

// @ds surface: text-artifact-card — substantial text artifact preview with a
// full-screen Open handoff. Presentation lives in src/style.css under the same
// surface name; the clipboard + react-aria wiring below is guardrailed and not
// designer-editable.

// @ds guardrail: do-not-edit — exact-copy clipboard boundary. The canonical source
// is written to the clipboard unaltered; the Open action is a pass-through into
// the existing viewer with no fetch, endpoint, ticket, download, or host-file read.
export interface TextArtifactCardProps {
  readonly block: NormalizedTextArtifactBlock;
  readonly onOpen?: (trigger?: HTMLButtonElement | null) => void;
}

const PREVIEW_LINES = 6;

export function TextArtifactCard({ block, onOpen }: TextArtifactCardProps) {
  // @ds guardrail: do-not-edit — exact-copy clipboard boundary (useCopyFeedback).
  const feedback = useCopyFeedback();
  const lines = displayLines(block.canonicalSource);
  const preview = lines.slice(0, PREVIEW_LINES).join('\n');
  const trustedLabel = textArtifactLabel(block.label);
  const canOpen = block.settled && block.canonicalSource.length > 0 && onOpen !== undefined;
  const openButtonRef = useRef<HTMLButtonElement>(null);
  return (
    <RichBlockFrame
      title={trustedLabel}
      eyebrow="Text artifact"
      metadata={[`${lines.length} lines`, `${block.canonicalSource.length} characters`]}
      {...(block.label === 'long-text' ? { status: 'Long text' } : {})}
      redaction={block.redaction}
      className="rich-text-artifact-card"
      actions={
        // @ds slot: actions — Copy text + full-screen Open handoff.
        // @ds guardrail: do-not-edit — react-aria Button wiring and the exact-copy
        // clipboard boundary; Open is a pass-through with no fetch/endpoint/ticket/
        // download/host-file read.
        feedback.canCopy || canOpen ? (
          <>
            {feedback.canCopy && (
              <Button
                className="rich-block-action"
                aria-label={feedback.actionLabel('text')}
                onPress={() => feedback.copy('text', block.canonicalSource)}
              >
                {feedback.actionLabel('text')}
              </Button>
            )}
            {canOpen && (
              <Button
                ref={openButtonRef}
                className="rich-block-action"
                onPress={() => onOpen?.(openButtonRef.current)}
              >
                Open full screen
              </Button>
            )}
          </>
        ) : undefined
      }
    >
      {/* @ds slot: preview — clipped text-artifact preview column. */}
      <div className="rich-text-artifact-preview">
        <pre>{preview}</pre>
      </div>
      {lines.length > PREVIEW_LINES && (
        <p className="rich-continuation">{lines.length - PREVIEW_LINES} more lines</p>
      )}
      {/* @ds guardrail: do-not-edit — polite live region announcing Copy outcomes. */}
      <p className="rich-copy-status" role="status" aria-live="polite">
        {feedback.announcement}
      </p>
    </RichBlockFrame>
  );
}

function textArtifactLabel(value: NormalizedTextArtifactBlock['label']): string {
  switch (value) {
    case 'prompt':
      return 'Prompt';
    case 'goal':
      return 'Goal';
    case 'plan':
      return 'Plan';
    case 'document':
      return 'Document';
    case 'text':
      return 'Text';
    case 'long-text':
      return 'Long text';
  }
}

function displayLines(value: string): string[] {
  const lines = value.split(/\r?\n/u);
  if (lines.at(-1) === '') lines.pop();
  return lines;
}

// app-mobile/src/pages/chat/rich-content/TextArtifactCard.svelte
<script lang="ts">
  import type { NormalizedTextArtifactBlock } from './normalizeTranscriptBlocks.js';
  import RichBlockFrame from './RichBlockFrame.svelte';
  import { useCopyFeedback } from './useCopyFeedback.svelte.js';
  import { hover } from '../../../shared/primitives/interactions.js';

  interface Props {
    block: NormalizedTextArtifactBlock;
    onOpen?: (trigger?: HTMLButtonElement | null) => void;
  }

  let { block, onOpen }: Props = $props();

  const PREVIEW_LINES = 6;

  const feedback = useCopyFeedback();
  const lines = $derived(displayLines(block.canonicalSource));
  const preview = $derived(lines.slice(0, PREVIEW_LINES).join('\n'));
  const trustedLabel = $derived(textArtifactLabel(block.label));
  const canOpen = $derived(
    block.settled && block.canonicalSource.length > 0 && onOpen !== undefined,
  );
  let openButton = $state<HTMLButtonElement | null>(null);

  function textArtifactLabel(value: NormalizedTextArtifactBlock['label']): string {
    switch (value) {
      case 'prompt':
        return 'Prompt';
      case 'goal':
        return 'Goal';
      case 'plan':
        return 'Plan';
      case 'document':
        return 'Document';
      case 'text':
        return 'Text';
      case 'long-text':
        return 'Long text';
    }
  }

  function displayLines(value: string): string[] {
    const result = value.split(/\r?\n/u);
    if (result.at(-1) === '') result.pop();
    return result;
  }
</script>

{#snippet actionsSnippet()}
  <!-- @ds slot: actions — Copy text + full-screen Open handoff. -->
  <!-- @ds guardrail: do-not-edit — the exact-copy clipboard boundary; Open is a
       pass-through with no fetch/endpoint/ticket/download/host-file read. -->
  {#if feedback.canCopy}
    <button
      class="rich-block-action"
      use:hover
      aria-label={feedback.actionLabel('text')}
      onclick={() => feedback.copy('text', block.canonicalSource)}
    >{feedback.actionLabel('text')}</button>
  {/if}
  {#if canOpen}
    <button class="rich-block-action" use:hover bind:this={openButton} onclick={() => onOpen?.(openButton)}
      >Open full screen</button>
  {/if}
{/snippet}

<RichBlockFrame
  title={trustedLabel}
  eyebrow="Text artifact"
  metadata={[`${lines.length} lines`, `${block.canonicalSource.length} characters`]}
  redaction={block.redaction}
  class="rich-text-artifact-card"
  {...(block.label === 'long-text' ? { status: 'Long text' } : {})}
  {...(feedback.canCopy || canOpen ? { actions: actionsSnippet } : {})}
>
  <!-- @ds slot: preview — clipped text-artifact preview column. -->
  <div class="rich-text-artifact-preview">
    <pre>{preview}</pre>
  </div>
  {#if lines.length > PREVIEW_LINES}
    <p class="rich-continuation">{lines.length - PREVIEW_LINES} more lines</p>
  {/if}
  <!-- @ds guardrail: do-not-edit — polite live region announcing Copy outcomes. -->
  <p class="rich-copy-status" role="status" aria-live="polite">{feedback.announcement}</p>
</RichBlockFrame>

<style>
  /* @ds surface: text-artifact-card — substantial text artifact preview with a
     full-screen Open handoff. */
  /* @ds slot: preview — clipped text-artifact preview column. */
  .rich-text-artifact-preview {
    max-block-size: 9.5rem;
    overflow: hidden;
    border-block: 1px solid var(--line);
  }

  /* @ds slot: preview — text-artifact lines (display serif, wrap-safe). */
  .rich-text-artifact-preview pre {
    margin: 0;
    padding-block: var(--space-3);
    color: var(--ink);
    font: 1rem/1.55 var(--font-display);
    white-space: pre-wrap;
    overflow-wrap: anywhere;
  }

  /* @ds slot: labels — text continuation caption (muted small type). */
  .rich-continuation {
    margin: var(--space-2) 0 0;
    color: var(--ink-muted);
    font-size: 0.75rem;
  }

  /* @ds state: copy — success · failure · unavailable. The Copy announcer line is a
     polite live region whose text carries the outcome; the presence styles are this. */
  /* @ds guardrail: do-not-edit — role="status" aria-live="polite" live region. */
  .rich-copy-status {
    min-block-size: 1.25rem;
    margin: var(--space-2) 0 0;
    color: var(--ink-muted);
    font-size: 0.75rem;
  }
</style>
