// app-mobile/src/pages/chat/artifacts/verified-image.svelte
<script module lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // MODULE: VERIFIED IMAGE
  // ───────────────────────────────────────────────────────────────────

  import type { InboundImageReadyBlock } from '@pi-remote/pi-rpc-protocol';

  import type { ArtifactResourceStatus } from './use-artifact-resource.svelte.js';
  import type { InboundImageLifecycleState } from './image-status.svelte';

  // ───────────────────────────────────────────────────────────────────
  // 1. TYPE DEFINITIONS
  // ───────────────────────────────────────────────────────────────────

  export interface VerifiedImageProps {
    readonly block: InboundImageReadyBlock;
    readonly sessionId: string;
    readonly aspectRatio: number;
    readonly enabled?: boolean;
    readonly forceLoad?: boolean;
    readonly lifecycleState?: InboundImageLifecycleState;
    readonly onStateChange?: (state: InboundImageLifecycleState) => void;
  }

  // ───────────────────────────────────────────────────────────────────
  // 2. HELPERS
  // ───────────────────────────────────────────────────────────────────

  function stateForResourceStatus(status: ArtifactResourceStatus): InboundImageLifecycleState | null {
    switch (status) {
      case 'loading':
        return 'thumbnail-fetching';
      case 'stalled':
        return 'stalled';
      case 'ready':
        return 'inline-ready';
      case 'offline':
        return 'offline-unavailable';
      case 'stale':
        return 'stale';
      case 'denied':
        return 'denied';
      case 'expired':
        return 'expired';
      case 'missing':
      case 'conflict':
        return 'revision-conflict';
      case 'revoked':
        return 'revoked';
      case 'corrupt':
        return 'corrupt';
      case 'rate-limited':
        return 'rate-limited';
      case 'aborted':
        return 'aborted';
      default:
        return null;
    }
  }
</script>

<script lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // 3. IMPORTS
  // ───────────────────────────────────────────────────────────────────

  import { demoInboundArtifactResource, isDemoMode } from '$shared/fixtures/demo.js';
  import { useArtifactResource } from './use-artifact-resource.svelte.js';

  import './verified-image.css';

  // ───────────────────────────────────────────────────────────────────
  // 4. PROPS
  // ───────────────────────────────────────────────────────────────────

  let {
    block,
    sessionId,
    aspectRatio,
    enabled = true,
    forceLoad = false,
    lifecycleState,
    onStateChange,
  }: VerifiedImageProps = $props();

  // ───────────────────────────────────────────────────────────────────
  // 5. LOCAL STATE
  // ───────────────────────────────────────────────────────────────────

  // svelte-ignore state_referenced_locally
  let nearViewport = $state(forceLoad || typeof IntersectionObserver === 'undefined');
  let imageFailed = $state(false);
  let wellEl = $state<HTMLDivElement | null>(null);
  let autoRetry = false;

  const resource = useArtifactResource(
    () => sessionId,
    () => block,
    () => ({
      enabled: enabled && (forceLoad || nearViewport),
      variant: 'thumbnail',
      requireImageDecode: true,
      ...(isDemoMode() ? { read: demoInboundArtifactResource } : {}),
    }),
  );

  // ───────────────────────────────────────────────────────────────────
  // 6. DERIVED STATE
  // ───────────────────────────────────────────────────────────────────

  const showPixels = $derived(
    !imageFailed &&
      resource.current.status === 'ready' &&
      resource.current.objectUrl !== null &&
      (lifecycleState === undefined ||
        lifecycleState === 'inline-ready' ||
        lifecycleState === 'full-fetching' ||
        lifecycleState === 'stalled' ||
        lifecycleState === 'full-degraded' ||
        lifecycleState === 'offline-loaded'),
  );

  // ───────────────────────────────────────────────────────────────────
  // 7. EFFECTS
  // ───────────────────────────────────────────────────────────────────

  $effect(() => {
    void block.id;
    void block.revision;
    void forceLoad;
    nearViewport = forceLoad || typeof IntersectionObserver === 'undefined';
    imageFailed = false;
    autoRetry = false;
  });

  $effect(() => {
    if (!enabled || forceLoad || nearViewport) return undefined;
    const element = wellEl;
    if (element === null || typeof IntersectionObserver === 'undefined') {
      nearViewport = true;
      return undefined;
    }
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting || entry.intersectionRatio > 0)) {
          nearViewport = true;
          observer.disconnect();
        }
      },
      { rootMargin: '200% 0px' },
    );
    observer.observe(element);
    return () => observer.disconnect();
  });

  $effect(() => {
    const status = resource.current.status;
    if (!enabled || (status !== 'relay-error' && status !== 'stalled')) {
      return undefined;
    }
    if (autoRetry) return undefined;
    autoRetry = true;
    const timer = window.setTimeout(() => resource.current.reload(), 750);
    return () => window.clearTimeout(timer);
  });

  $effect(() => {
    const status = resource.current.status;
    if (lifecycleState !== undefined || onStateChange === undefined) return;
    const next = stateForResourceStatus(status);
    if (next !== null) onStateChange(next);
  });

</script>

<div
  bind:this={wellEl}
  class={showPixels ? 'inbound-image-well inbound-image-well-ready' : 'inbound-image-well'}
  data-image-well={showPixels ? 'verified' : 'placeholder'}
  data-verified-image={showPixels ? 'true' : undefined}
  data-image-state={lifecycleState ?? stateForResourceStatus(resource.current.status) ?? 'deferred'}
  data-no-pixels={showPixels ? undefined : 'true'}
  style:aspect-ratio={String(aspectRatio)}
  aria-hidden="true"
>
  {#if showPixels}
    <img
      class="inbound-image-thumbnail"
      src={resource.current.objectUrl}
      alt=""
      draggable={false}
      onerror={() => {
        imageFailed = true;
        resource.current.close();
        onStateChange?.('corrupt');
      }}
    />
  {:else}
    <span class="inbound-image-placeholder-pattern"></span>
  {/if}
</div>

<!-- @ds surface: inbound-image-thumbnail — the decoded inbound image inside the well. Decomposed into this co-located CSS file;
     the well itself (.inbound-image-well) is shared with ImagePlaceholder and stays global.
     Values unchanged. -->

// apps/pi-remote-web/src/artifacts/VerifiedImage.tsx
import { useEffect, useRef, useState } from 'react';
import type { InboundImageReadyBlock } from '@pi-remote/pi-rpc-protocol';

import { demoInboundArtifactResource, isDemoMode } from '../demo.js';
import { useArtifactResource, type ArtifactResourceStatus } from './useArtifactResource.js';
import type { InboundImageLifecycleState } from './ImageStatus.js';

export interface VerifiedImageProps {
  readonly block: InboundImageReadyBlock;
  readonly sessionId: string;
  readonly aspectRatio: number;
  readonly enabled?: boolean;
  readonly forceLoad?: boolean;
  readonly state?: InboundImageLifecycleState;
  readonly onStateChange?: (state: InboundImageLifecycleState) => void;
}

function stateForResourceStatus(status: ArtifactResourceStatus): InboundImageLifecycleState | null {
  switch (status) {
    case 'loading':
      return 'thumbnail-fetching';
    case 'stalled':
      return 'stalled';
    case 'ready':
      return 'inline-ready';
    case 'offline':
      return 'offline-unavailable';
    case 'stale':
      return 'stale';
    case 'denied':
      return 'denied';
    case 'expired':
      return 'expired';
    case 'missing':
    case 'conflict':
      return 'revision-conflict';
    case 'revoked':
      return 'revoked';
    case 'corrupt':
      return 'corrupt';
    case 'rate-limited':
      return 'rate-limited';
    case 'aborted':
      return 'aborted';
    default:
      return null;
  }
}

export function VerifiedImage({
  block,
  sessionId,
  aspectRatio,
  enabled = true,
  forceLoad = false,
  state,
  onStateChange,
}: VerifiedImageProps) {
  const [nearViewport, setNearViewport] = useState(
    forceLoad || typeof IntersectionObserver === 'undefined',
  );
  const [imageFailed, setImageFailed] = useState(false);
  const wellRef = useRef<HTMLDivElement>(null);
  const autoRetryRef = useRef(false);
  const reloadRef = useRef<() => void>(() => undefined);

  useEffect(() => {
    setNearViewport(forceLoad || typeof IntersectionObserver === 'undefined');
    setImageFailed(false);
    autoRetryRef.current = false;
  }, [block.id, block.revision, forceLoad]);

  useEffect(() => {
    if (!enabled || forceLoad || nearViewport) return undefined;
    const element = wellRef.current;
    if (element === null || typeof IntersectionObserver === 'undefined') {
      setNearViewport(true);
      return undefined;
    }
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting || entry.intersectionRatio > 0)) {
          setNearViewport(true);
          observer.disconnect();
        }
      },
      { rootMargin: '200% 0px' },
    );
    observer.observe(element);
    return () => observer.disconnect();
  }, [enabled, forceLoad, nearViewport]);

  const resource = useArtifactResource(sessionId, block, {
    enabled: enabled && (forceLoad || nearViewport),
    variant: 'thumbnail',
    requireImageDecode: true,
    ...(isDemoMode() ? { read: demoInboundArtifactResource } : {}),
  });
  reloadRef.current = resource.reload;

  useEffect(() => {
    if (!enabled || (resource.status !== 'relay-error' && resource.status !== 'stalled')) {
      return undefined;
    }
    if (autoRetryRef.current) return undefined;
    autoRetryRef.current = true;
    const timer = window.setTimeout(() => reloadRef.current(), 750);
    return () => window.clearTimeout(timer);
  }, [enabled, resource.status]);

  useEffect(() => {
    if (state !== undefined || onStateChange === undefined) return;
    const next = stateForResourceStatus(resource.status);
    if (next !== null) onStateChange(next);
  }, [onStateChange, resource.status, state]);

  const showPixels =
    !imageFailed &&
    resource.status === 'ready' &&
    resource.objectUrl !== null &&
    (state === undefined ||
      state === 'inline-ready' ||
      state === 'full-fetching' ||
      state === 'stalled' ||
      state === 'full-degraded' ||
      state === 'offline-loaded');
  const style = { aspectRatio: String(aspectRatio) };

  return (
    <div
      ref={wellRef}
      className={showPixels ? 'inbound-image-well inbound-image-well-ready' : 'inbound-image-well'}
      data-image-well={showPixels ? 'verified' : 'placeholder'}
      data-verified-image={showPixels ? 'true' : undefined}
      data-image-state={state ?? stateForResourceStatus(resource.status) ?? 'deferred'}
      data-no-pixels={showPixels ? undefined : 'true'}
      style={style}
      aria-hidden="true"
    >
      {showPixels ? (
        <img
          className="inbound-image-thumbnail"
          src={resource.objectUrl}
          alt=""
          draggable={false}
          onError={() => {
            setImageFailed(true);
            resource.close();
            onStateChange?.('corrupt');
          }}
        />
      ) : (
        <span className="inbound-image-placeholder-pattern" />
      )}
    </div>
  );
}
