// app-mobile/src/pages/chat/chrome/command-option.svelte
<script module lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // MODULE: Slash Command Option (safe text-only row)
  // ───────────────────────────────────────────────────────────────────
  // One text-only listbox option. The canonical name is isolated LTR and
  // Never translated, matched graphemes are emphasized structurally, and
  // Every other line renders authoritative relay metadata as plain text.
  // Rows are never focusable, never nest interactive descendants, and a
  // Press only ever completes as an insertion request for an enabled row —
  // Disabled rows surface their disclosed reason instead. Any control or
  // Bidi-override character that somehow reaches the client is replaced for
  // Display only; insertion always uses the canonical DTO string.

  // ───────────────────────────────────────────────────────────────────
  // 1. IMPORTS
  // ───────────────────────────────────────────────────────────────────

  import type { RankedHostCommand } from '$shared/commands/rank-host-commands.js';

  // ───────────────────────────────────────────────────────────────────
  // 2. HELPERS
  // ───────────────────────────────────────────────────────────────────

  /** The stable option id the composer's aria-activedescendant references. */
  export function optionId(name: string): string {
    return `slash-option-${name}`;
  }

  // ───────────────────────────────────────────────────────────────────
  // 3. CONSTANTS
  // ───────────────────────────────────────────────────────────────────

  /** Display-only escape: canonical names never contain these, but visible text is
   *  A security surface. The replacement is display-only; insertion always uses the
   *  Canonical DTO string unchanged.
   *  @ds guardrail: escaping — Unsafe/bidi-override characters are display-replaced. */
  export const UNSAFE_NAME_CHARACTERS = /[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/g;

  // ───────────────────────────────────────────────────────────────────
  // 4. HELPERS
  // ───────────────────────────────────────────────────────────────────

  export function escapeUnsafeName(name: string): string {
    return name.replace(UNSAFE_NAME_CHARACTERS, '\uFFFD');
  }

  // ───────────────────────────────────────────────────────────────────
  // 5. TYPE DEFINITIONS
  // ───────────────────────────────────────────────────────────────────

  export interface CommandOptionProps {
    readonly command: RankedHostCommand;
    /** Whether this row carries the virtual focus (aria-activedescendant target). */
    readonly active: boolean;
    /** Completed-press insertion request for an enabled row. */
    readonly onInsert: (name: string) => void;
    /** Completed-press announcement for a disabled row's disclosed reason. */
    readonly onDisabledPress: (reason: string) => void;
  }

  // ───────────────────────────────────────────────────────────────────
  // 6. HELPERS
  // ───────────────────────────────────────────────────────────────────

  function sourceLabel(source: RankedHostCommand['source']): string {
    switch (source) {
      case 'extension':
        return 'Extension';
      case 'prompt':
        return 'Prompt';
      case 'skill':
        return 'Skill';
    }
  }
</script>

<script lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // 7. IMPORTS
  // ───────────────────────────────────────────────────────────────────

  import { commandGraphemes } from '$shared/commands/rank-host-commands.js';

  import './command-option.css';

  // ───────────────────────────────────────────────────────────────────
  // 8. PROPS
  // ───────────────────────────────────────────────────────────────────

  let { command, active, onInsert, onDisabledPress }: CommandOptionProps = $props();

  // ───────────────────────────────────────────────────────────────────
  // 9. LOCAL STATE
  // ───────────────────────────────────────────────────────────────────

  /** A pointer drag farther than this cancels activation (no accidental tap-drag inserts). */
  const DRAG_SLOP_PX = 10;

  // Non-reactive press tracking: a re-render must not reset the origin or the
  // Drag-cancel flag mid-gesture (useRef equivalent).
  let pressOrigin: { x: number; y: number } | null = null;
  let dragged = false;

  // ───────────────────────────────────────────────────────────────────
  // 10. DERIVED STATE
  // ───────────────────────────────────────────────────────────────────

  const graphemes = $derived(commandGraphemes(escapeUnsafeName(command.name)));
  const matched = (index: number) =>
    command.matchRanges.some((range) => range.start <= index && index < range.end);

  // ───────────────────────────────────────────────────────────────────
  // 11. HANDLERS
  // ───────────────────────────────────────────────────────────────────

  const onPointerDown = (event: PointerEvent) => {
    // Focus stays in the textarea: no focus steal, no text selection, no
    // Long-press context menu, no iOS callout.
    event.preventDefault();
    pressOrigin = { x: event.clientX, y: event.clientY };
    dragged = false;
  };
  // WebKit compatibility: cancel the mouse path as well as the pointer path.
  const onMouseDown = (event: MouseEvent) => {
    event.preventDefault();
  };
  const onPointerMove = (event: PointerEvent) => {
    const origin = pressOrigin;
    if (origin === null) return;
    if (
      Math.abs(event.clientX - origin.x) > DRAG_SLOP_PX ||
      Math.abs(event.clientY - origin.y) > DRAG_SLOP_PX
    ) {
      dragged = true;
    }
  };
  const onClick = () => {
    if (dragged) {
      dragged = false;
      pressOrigin = null;
      return;
    }
    pressOrigin = null;
    // A completed row press is only ever an insertion request for an enabled row
    // (or a disclosed-reason announcement for a disabled one); it never submits.
    // @ds guardrail: fail-closed — Press requests insertion, never submission.
    if (command.enabled) {
      onInsert(command.name);
    } else if (command.disabledReason !== null) {
      onDisabledPress(command.disabledReason);
    }
  };

</script>

<!-- This row only restyles; its role, aria wiring, and virtual-focus hook are frozen. -->
<!-- @ds surface: slash-autocomplete -->
<!-- @ds guardrail: React-aria wiring — Option role, aria-selected/aria-disabled, data-focused virtual focus, and the focus-preserving press path. -->

<!-- svelte-ignore a11y_interactive_supports_focus -->
<!-- svelte-ignore a11y_click_events_have_key_events -->
<div
  role="option"
  id={optionId(command.name)}
  aria-selected={command.enabled ? active : undefined}
  aria-disabled={command.enabled ? undefined : true}
  data-focused={active || undefined}
  class="slash-option"
  onpointerdown={onPointerDown}
  onmousedown={onMouseDown}
  onpointermove={onPointerMove}
  onclick={onClick}
>
  <!-- @ds slot: label — the command name, match emphasis, and argument hint. -->
  <span class="slash-name-line">
    <bdi dir="ltr" translate="no" class="slash-name"
      >{'/'}{#each graphemes as grapheme, index (`${index}-${grapheme}`)}{#if matched(index)}<strong
          class="slash-match">{grapheme}</strong
        >{:else}<span>{grapheme}</span>{/if}{/each}</bdi
    >
    {#if command.argumentHint !== null && command.argumentHint !== undefined}
      <span class="slash-hint" dir="auto">
        {command.argumentHint}
      </span>
    {/if}
  </span>
  {#if command.enabled}
    {#if command.description !== null}
      <span class="slash-desc" dir="auto">
        {command.description}
      </span>
    {/if}
  {:else}
    <!-- @ds state: disabled-with-reason — a disabled row surfaces its disclosed reason. -->
    <span class="slash-disabled-reason" dir="auto">
      {command.disabledReason !== null ? command.disabledReason : 'Unavailable: not disclosed'}
    </span>
  {/if}
  <!-- @ds slot: binding — the authoritative source binding and confirmation hint. -->
  <span class="slash-meta">
    <span class="slash-source">{sourceLabel(command.source)}</span>
    {#if command.requiresConfirmation}<span class="slash-confirm">Asks first</span>{/if}
  </span>
</div>

<!-- @ds surface: slash-autocomplete — one text-only listbox option. Decomposed into this co-located CSS file;
     slash-option / name / match / hint / desc / meta and their states are owned solely by this
     component so they move with it. Values unchanged. -->

// apps/pi-remote-web/src/CommandOption.tsx
// ───────────────────────────────────────────────────────────────────
// MODULE: Slash Command Option (safe text-only row)
// ───────────────────────────────────────────────────────────────────
// One text-only listbox option. The canonical name is isolated LTR and
// never translated, matched graphemes are emphasized structurally, and
// every other line renders authoritative relay metadata as plain text.
// Rows are never focusable, never nest interactive descendants, and a
// press only ever completes as an insertion request for an enabled row —
// disabled rows surface their disclosed reason instead. Any control or
// bidi-override character that somehow reaches the client is replaced for
// display only; insertion always uses the canonical DTO string.

import { useRef } from 'react';
import type { PointerEvent as ReactPointerEvent, MouseEvent as ReactMouseEvent } from 'react';

import { commandGraphemes, type RankedHostCommand } from './rankHostCommands.js';

/** The stable option id the composer's aria-activedescendant references. */
export function optionId(name: string): string {
  return `slash-option-${name}`;
}

/** Display-only escape: canonical names never contain these, but visible text is
 *  a security surface. The replacement is display-only; insertion always uses the
 *  canonical DTO string unchanged.
 *  @ds guardrail: escaping — unsafe/bidi-override characters are display-replaced. */
const UNSAFE_NAME_CHARACTERS = /[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/g;

export function escapeUnsafeName(name: string): string {
  return name.replace(UNSAFE_NAME_CHARACTERS, '\uFFFD');
}

export interface CommandOptionProps {
  readonly command: RankedHostCommand;
  /** Whether this row carries the virtual focus (aria-activedescendant target). */
  readonly active: boolean;
  /** Completed-press insertion request for an enabled row. */
  readonly onInsert: (name: string) => void;
  /** Completed-press announcement for a disabled row's disclosed reason. */
  readonly onDisabledPress: (reason: string) => void;
}

/** A pointer drag farther than this cancels activation (no accidental tap-drag inserts). */
const DRAG_SLOP_PX = 10;

export function CommandOption({ command, active, onInsert, onDisabledPress }: CommandOptionProps) {
  const { name, description, source, enabled, disabledReason, requiresConfirmation, argumentHint } =
    command;
  const pressOriginRef = useRef<{ x: number; y: number } | null>(null);
  const draggedRef = useRef(false);

  const onPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    // Focus stays in the textarea: no focus steal, no text selection, no
    // long-press context menu, no iOS callout.
    event.preventDefault();
    pressOriginRef.current = { x: event.clientX, y: event.clientY };
    draggedRef.current = false;
  };
  // WebKit compatibility: cancel the mouse path as well as the pointer path.
  const onMouseDown = (event: ReactMouseEvent<HTMLDivElement>) => {
    event.preventDefault();
  };
  const onPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    const origin = pressOriginRef.current;
    if (origin === null) return;
    if (
      Math.abs(event.clientX - origin.x) > DRAG_SLOP_PX ||
      Math.abs(event.clientY - origin.y) > DRAG_SLOP_PX
    ) {
      draggedRef.current = true;
    }
  };
  const onClick = () => {
    if (draggedRef.current) {
      draggedRef.current = false;
      pressOriginRef.current = null;
      return;
    }
    pressOriginRef.current = null;
    // A completed row press is only ever an insertion request for an enabled row
    // (or a disclosed-reason announcement for a disabled one); it never submits.
    // @ds guardrail: fail-closed — press requests insertion, never submission.
    if (enabled) {
      onInsert(name);
    } else if (disabledReason !== null) {
      onDisabledPress(disabledReason);
    }
  };

  const graphemes = commandGraphemes(escapeUnsafeName(name));
  const matched = (index: number) =>
    command.matchRanges.some((range) => range.start <= index && index < range.end);

  return (
    // This row only restyles; its role, aria wiring, and virtual-focus hook are frozen.
    // @ds surface: slash-autocomplete
    // @ds guardrail: react-aria wiring — option role, aria-selected/aria-disabled,
    //                data-focused virtual focus, and the focus-preserving press path.
    <div
      role="option"
      id={optionId(name)}
      aria-selected={enabled ? active : undefined}
      aria-disabled={enabled ? undefined : true}
      data-focused={active || undefined}
      className="slash-option"
      onPointerDown={onPointerDown}
      onMouseDown={onMouseDown}
      onPointerMove={onPointerMove}
      onClick={onClick}
    >
      {/* @ds slot: label — the command name, match emphasis, and argument hint. */}
      <span className="slash-name-line">
        <bdi dir="ltr" translate="no" className="slash-name">
          {'/'}
          {graphemes.map((grapheme, index) =>
            matched(index) ? (
              <strong className="slash-match" key={`${index}-${grapheme}`}>
                {grapheme}
              </strong>
            ) : (
              <span key={`${index}-${grapheme}`}>{grapheme}</span>
            ),
          )}
        </bdi>
        {argumentHint !== null && argumentHint !== undefined && (
          <span className="slash-hint" dir="auto">
            {argumentHint}
          </span>
        )}
      </span>
      {enabled ? (
        description !== null && (
          <span className="slash-desc" dir="auto">
            {description}
          </span>
        )
      ) : (
        // @ds state: disabled-with-reason — a disabled row surfaces its disclosed reason.
        <span className="slash-disabled-reason" dir="auto">
          {disabledReason !== null ? disabledReason : 'Unavailable: not disclosed'}
        </span>
      )}
      {/* @ds slot: binding — the authoritative source binding and confirmation hint. */}
      <span className="slash-meta">
        <span className="slash-source">{sourceLabel(source)}</span>
        {requiresConfirmation && <span className="slash-confirm">Asks first</span>}
      </span>
    </div>
  );
}

function sourceLabel(source: RankedHostCommand['source']): string {
  switch (source) {
    case 'extension':
      return 'Extension';
    case 'prompt':
      return 'Prompt';
    case 'skill':
      return 'Skill';
  }
}
