// apps/pi-remote-web/src/features/ask-question/AskQuestionCard.tsx
import type { AskQuestionTranscriptMeta } from '@pi-remote/pi-rpc-protocol';
import { useCallback, useEffect, useId, useState } from 'react';

import { fetchAskQuestionDisplay } from '../../relay.js';
import { releaseAskQuestionEphemeral, setAskQuestionDisplay } from './askQuestionEphemeralStore.js';
import {
  isAskQuestionTerminalState,
  toAskQuestionViewModel,
  transcriptStatusToUiState,
  type AskQuestionViewModel,
} from './askQuestionTypes.js';
import { AskQuestionFreeText } from './AskQuestionFreeText.js';
import { AskQuestionOptionList } from './AskQuestionOptionList.js';
import { AskQuestionPrompt } from './AskQuestionPrompt.js';
import { AskQuestionStatus } from './AskQuestionStatus.js';
import { AskQuestionSubmitButton } from './AskQuestionSubmitButton.js';
import { useAskQuestionKeyboardNavigation } from './useAskQuestionKeyboardNavigation.js';
import { useAskQuestionMutation } from './useAskQuestionMutation.js';
import { useAskQuestionState } from './useAskQuestionState.js';

export interface AskQuestionCardProps {
  readonly block: AskQuestionTranscriptMeta;
  readonly sessionId?: string;
  readonly canAnswer?: boolean;
  readonly principal?: string | undefined;
}

export function AskQuestionCard({
  block,
  canAnswer = true,
  principal,
}: AskQuestionCardProps) {
  const [viewModel, setViewModel] = useState<AskQuestionViewModel | null>(null);
  const stateApi = useAskQuestionState(viewModel, {
    initialState: transcriptStatusToUiState(block.status),
  });
  const resolveResult = stateApi.resolveResult;
  const applyTranscriptStatus = stateApi.applyTranscriptStatus;
  const onResult = useCallback(
    (result: Parameters<typeof resolveResult>[0]) => resolveResult(result),
    [resolveResult],
  );
  const mutation = useAskQuestionMutation({
    sessionId: block.sessionId,
    viewModel,
    principal,
    onResult,
  });

  const labelId = useId();
  const optionsLabelId = useId();
  const statusId = useId();
  const errorId = useId();
  const lifecyclePhase = transcriptStatusToUiState(block.status);
  const lifecycleLocks =
    lifecyclePhase === 'submitting' || isAskQuestionTerminalState(lifecyclePhase);
  const effectivePhase =
    viewModel === null
      ? lifecyclePhase
      : lifecycleLocks
        ? lifecyclePhase
        : stateApi.state.phase;
  const effectiveState =
    effectivePhase === stateApi.state.phase
      ? stateApi.state
      : { ...stateApi.state, phase: effectivePhase };
  const terminal = isAskQuestionTerminalState(effectivePhase);
  const submitting = effectivePhase === 'submitting' || mutation.submitting;
  const controlsDisabled = !canAnswer || submitting || terminal;
  const validationVisible =
    stateApi.validationMessage !== null &&
    (effectivePhase === 'selecting' || effectivePhase === 'error');
  const beginSubmit = stateApi.beginSubmit;
  const submitMutation = mutation.submit;
  const submitAnswer = useCallback(() => {
    if (terminal || submitting) return;
    const intent = beginSubmit();
    if (intent !== null) void submitMutation(intent);
  }, [beginSubmit, submitting, submitMutation, terminal]);
  const cardRef = useAskQuestionKeyboardNavigation({
    identity: `${block.questionId}:${block.presentedRevision}`,
    enabled: viewModel !== null && canAnswer && !submitting && !terminal,
    terminal,
    optionCount: viewModel?.display.options.length ?? 0,
    hasFreeText: viewModel?.display.freeText.allowed ?? false,
    freeTextRequired: viewModel?.display.freeText.required ?? false,
    labelId,
    optionsLabelId,
    statusId,
    errorId,
    errorVisible: validationVisible,
    submit: submitAnswer,
  });

  useEffect(() => {
    const controller = new AbortController();
    let active = true;
    setViewModel(null);
    void fetchAskQuestionDisplay(
      block.sessionId,
      block.questionId,
      block.presentedRevision,
      controller.signal,
    )
      .then((payload) => {
        const guarded = toAskQuestionViewModel(payload);
        if (
          !active ||
          guarded === null ||
          guarded.sessionId !== block.sessionId ||
          guarded.questionId !== block.questionId ||
          guarded.revision !== block.presentedRevision
        ) {
          return;
        }
        setAskQuestionDisplay(guarded);
        setViewModel(guarded);
      })
      .catch(() => undefined);
    return () => {
      active = false;
      controller.abort();
      releaseAskQuestionEphemeral(block.questionId, block.presentedRevision);
    };
  }, [block.presentedRevision, block.questionId, block.sessionId]);

  useEffect(() => {
    applyTranscriptStatus(block.status);
  }, [applyTranscriptStatus, block.status]);

  useEffect(() => {
    if (viewModel !== null && isAskQuestionTerminalState(stateApi.state.phase)) {
      releaseAskQuestionEphemeral(viewModel.questionId, viewModel.revision);
    }
    return () => {
      if (viewModel !== null && isAskQuestionTerminalState(stateApi.state.phase)) {
        releaseAskQuestionEphemeral(viewModel.questionId, viewModel.revision);
      }
    };
  }, [stateApi.state.phase, viewModel]);

  if (viewModel === null) {
    return (
      <article
        ref={cardRef}
        className="ask-question-card ask-question-card-loading"
        data-ask-question-card
        role="status"
        aria-live="polite"
        aria-label="Loading question"
        tabIndex={-1}
      >
        <span className="sr-only">Loading question</span>
      </article>
    );
  }

  return (
    <article
      ref={cardRef}
      className={`ask-question-card ask-question-card-${effectivePhase}`}
      data-ask-question-card
      data-ask-question-phase={effectivePhase}
      role="region"
      aria-label="Ask question"
      aria-labelledby={labelId}
      aria-describedby={statusId}
      aria-busy={submitting}
      tabIndex={-1}
    >
      <AskQuestionPrompt viewModel={viewModel} />
      {viewModel.requiresReadOnlyHint && (
        <p className="ask-question-read-only-hint">
          Answers are sent only while this authenticated read-only session is active.
        </p>
      )}
      {!terminal && (
        <form
          className="ask-question-form"
          aria-describedby={statusId}
          onSubmit={(event) => {
            event.preventDefault();
            submitAnswer();
          }}
        >
          {viewModel.display.options.length > 0 && (
            <span id={optionsLabelId} className="sr-only">
              Answer options
            </span>
          )}
          <AskQuestionOptionList
            viewModel={viewModel}
            selectedOptionIds={stateApi.state.selectedOptionIds}
            disabled={controlsDisabled}
            onToggle={stateApi.selectOption}
          />
          <AskQuestionFreeText
            viewModel={viewModel}
            value={stateApi.state.freeText}
            disabled={controlsDisabled}
            invalid={validationVisible}
            onChange={stateApi.setFreeText}
          />
          {validationVisible && (
            <p
              id={errorId}
              className="ask-question-validation"
              role="alert"
              aria-live="assertive"
              aria-atomic="true"
            >
              {stateApi.validationMessage}
            </p>
          )}
          <AskQuestionSubmitButton
            disabled={!canAnswer || !stateApi.canSubmit || submitting || terminal}
          />
        </form>
      )}
      <AskQuestionStatus state={effectiveState} />
      {effectiveState.phase === 'answered-immutable' && effectiveState.errorReason === null && (
        <p className="ask-question-answered-line" aria-hidden="true">
          Answer accepted by Pi.
        </p>
      )}
      {!canAnswer && !terminal && (
        <p className="ask-question-read-only-hint">Reconnect before submitting an answer.</p>
      )}
    </article>
  );
}

// src/mobile-app/src/lib/features/ask-question/AskQuestionCard.svelte
<script module lang="ts">
  import type { AskQuestionTranscriptMeta } from '@pi-remote/pi-rpc-protocol';

  export interface AskQuestionCardProps {
    readonly block: AskQuestionTranscriptMeta;
    readonly sessionId?: string;
    readonly canAnswer?: boolean;
    readonly principal?: string | undefined;
  }

  let askQuestionUidSequence = 0;
</script>

<script lang="ts">
  import { fetchAskQuestionDisplay } from '../../../relay.js';
  import {
    releaseAskQuestionEphemeral,
    setAskQuestionDisplay,
  } from '../../../features/ask-question/askQuestionEphemeralStore.js';
  import {
    isAskQuestionTerminalState,
    toAskQuestionViewModel,
    transcriptStatusToUiState,
    type AskQuestionViewModel,
  } from '../../../features/ask-question/askQuestionTypes.js';
  import AskQuestionFreeText from './AskQuestionFreeText.svelte';
  import AskQuestionOptionList from './AskQuestionOptionList.svelte';
  import AskQuestionPrompt from './AskQuestionPrompt.svelte';
  import AskQuestionStatus from './AskQuestionStatus.svelte';
  import AskQuestionSubmitButton from './AskQuestionSubmitButton.svelte';
  import { useAskQuestionKeyboardNavigation } from './useAskQuestionKeyboardNavigation.svelte.js';
  import { useAskQuestionMutation } from './useAskQuestionMutation.svelte.js';
  import { useAskQuestionState } from './useAskQuestionState.svelte.js';

  let { block, canAnswer = true, principal }: AskQuestionCardProps = $props();

  // @ds surface: ask-question — the one-use interactive question card; slot seams below.
  // @ds guardrail: one-use ticketed, revision-bound, FAIL-CLOSED mutation path. The ticket,
  //   revision binding, non-optimistic submit, and keyboard/a11y wiring live in the hooks
  //   (useAskQuestionState / useAskQuestionMutation / useAskQuestionKeyboardNavigation) and are
  //   NOT designer-editable. Only style.css @ds surface: ask-question is editable.
  let viewModel = $state<AskQuestionViewModel | null>(null);
  let cardEl = $state<HTMLElement | null>(null);

  const stateApi = useAskQuestionState(
    () => viewModel,
    () => transcriptStatusToUiState(block.status),
  );
  const mutation = useAskQuestionMutation(
    () => block.sessionId,
    () => viewModel,
    () => principal,
    stateApi.resolveResult,
  );

  const uid = `ask-question-${(askQuestionUidSequence += 1)}`;
  const labelId = `${uid}-label`;
  const optionsLabelId = `${uid}-options`;
  const statusId = `${uid}-status`;
  const errorId = `${uid}-error`;

  const lifecyclePhase = $derived(transcriptStatusToUiState(block.status));
  const lifecycleLocks = $derived(
    lifecyclePhase === 'submitting' || isAskQuestionTerminalState(lifecyclePhase),
  );
  const effectivePhase = $derived(
    viewModel === null ? lifecyclePhase : lifecycleLocks ? lifecyclePhase : stateApi.state.phase,
  );
  const effectiveState = $derived(
    effectivePhase === stateApi.state.phase
      ? stateApi.state
      : { ...stateApi.state, phase: effectivePhase },
  );
  const terminal = $derived(isAskQuestionTerminalState(effectivePhase));
  const submitting = $derived(effectivePhase === 'submitting' || mutation.submitting);
  const controlsDisabled = $derived(!canAnswer || submitting || terminal);
  const validationVisible = $derived(
    stateApi.validationMessage !== null &&
      (effectivePhase === 'selecting' || effectivePhase === 'error'),
  );

  function submitAnswer(): void {
    if (terminal || submitting) return;
    const intent = stateApi.beginSubmit();
    if (intent !== null) void mutation.submit(intent);
  }

  useAskQuestionKeyboardNavigation(
    () => cardEl,
    () => ({
      identity: `${block.questionId}:${block.presentedRevision}`,
      enabled: viewModel !== null && canAnswer && !submitting && !terminal,
      terminal,
      optionCount: viewModel?.display.options.length ?? 0,
      hasFreeText: viewModel?.display.freeText.allowed ?? false,
      freeTextRequired: viewModel?.display.freeText.required ?? false,
      labelId,
      optionsLabelId,
      statusId,
      errorId,
      errorVisible: validationVisible,
      submit: submitAnswer,
    }),
  );

  $effect(() => {
    const sessionId = block.sessionId;
    const questionId = block.questionId;
    const presentedRevision = block.presentedRevision;
    const controller = new AbortController();
    let active = true;
    viewModel = null;
    void fetchAskQuestionDisplay(sessionId, questionId, presentedRevision, controller.signal)
      .then((payload) => {
        const guarded = toAskQuestionViewModel(payload);
        if (
          !active ||
          guarded === null ||
          guarded.sessionId !== sessionId ||
          guarded.questionId !== questionId ||
          guarded.revision !== presentedRevision
        ) {
          return;
        }
        setAskQuestionDisplay(guarded);
        viewModel = guarded;
      })
      .catch(() => undefined);
    return () => {
      active = false;
      controller.abort();
      releaseAskQuestionEphemeral(questionId, presentedRevision);
    };
  });

  $effect(() => {
    stateApi.applyTranscriptStatus(block.status);
  });

  $effect(() => {
    const vm = viewModel;
    const phase = stateApi.state.phase;
    if (vm !== null && isAskQuestionTerminalState(phase)) {
      releaseAskQuestionEphemeral(vm.questionId, vm.revision);
    }
    return () => {
      if (vm !== null && isAskQuestionTerminalState(phase)) {
        releaseAskQuestionEphemeral(vm.questionId, vm.revision);
      }
    };
  });
</script>

{#if viewModel === null}
  <!-- @ds state: loading — the display is being fetched; no interactive controls yet. -->
  <article
    bind:this={cardEl}
    class="ask-question-card ask-question-card-loading"
    data-ask-question-card="true"
    role="status"
    aria-live="polite"
    aria-label="Loading question"
    tabindex="-1"
  >
    <span class="sr-only">Loading question</span>
  </article>
{:else}
  <article
    bind:this={cardEl}
    class={`ask-question-card ask-question-card-${effectivePhase}`}
    data-ask-question-card="true"
    data-ask-question-phase={effectivePhase}
    role="region"
    aria-label="Ask question"
    aria-labelledby={labelId}
    aria-describedby={statusId}
    aria-busy={submitting}
    tabindex="-1"
  >
    <!-- @ds slot: prompt — question eyebrow + display headline. -->
    <AskQuestionPrompt {viewModel} />
    <!-- @ds slot: read-only-hint — note shown while this authenticated read-only session gates answers. -->
    {#if viewModel.requiresReadOnlyHint}
      <p class="ask-question-read-only-hint">
        Answers are sent only while this authenticated read-only session is active.
      </p>
    {/if}
    <!-- @ds slot: form — answer controls; the guarded one-use submit mutation is not editable. -->
    {#if !terminal}
      <form
        class="ask-question-form"
        aria-describedby={statusId}
        onsubmit={(event) => {
          event.preventDefault();
          submitAnswer();
        }}
      >
        {#if viewModel.display.options.length > 0}
          <span id={optionsLabelId} class="sr-only">Answer options</span>
        {/if}
        <!-- @ds slot: options — the option-row list + selection, disabled in guarded states. -->
        <AskQuestionOptionList
          {viewModel}
          selectedOptionIds={stateApi.state.selectedOptionIds}
          disabled={controlsDisabled}
          onToggle={stateApi.selectOption}
        />
        <!-- @ds slot: free-text — optional/required response textarea. -->
        <AskQuestionFreeText
          {viewModel}
          value={stateApi.state.freeText}
          disabled={controlsDisabled}
          invalid={validationVisible}
          onChange={stateApi.setFreeText}
        />
        {#if validationVisible}
          <p
            id={errorId}
            class="ask-question-validation"
            role="alert"
            aria-live="assertive"
            aria-atomic="true"
          >
            {stateApi.validationMessage}
          </p>
        {/if}
        <!-- @ds slot: submit — the guarded one-use submit button; disabled binding preserved. -->
        <AskQuestionSubmitButton disabled={!canAnswer || !stateApi.canSubmit || submitting || terminal} />
      </form>
    {/if}
    <!-- @ds slot: status — live form-state line (sent ✓ · error ! · idle •). -->
    <AskQuestionStatus state={effectiveState} />
    <!-- @ds state: sent — answer accepted by Pi; the immutable ✓ line. -->
    {#if effectiveState.phase === 'answered-immutable' && effectiveState.errorReason === null}
      <p class="ask-question-answered-line" aria-hidden="true">Answer accepted by Pi.</p>
    {/if}
    <!-- @ds slot: read-only-hint — reconnect note shown when the session cannot answer. -->
    {#if !canAnswer && !terminal}
      <p class="ask-question-read-only-hint">Reconnect before submitting an answer.</p>
    {/if}
  </article>
{/if}
