// src/mobile-app/src/lib/features/ask-question/AskQuestionSubmitButton.svelte
<script module lang="ts">
  export interface AskQuestionSubmitButtonProps {
    readonly disabled: boolean;
  }
</script>

<script lang="ts">
  let { disabled }: AskQuestionSubmitButtonProps = $props();
</script>

<!-- @ds slot: submit — the form's guarded one-use submit button; disabled binding preserved. -->
<button type="submit" class="ask-question-submit" {disabled}>Submit answer</button>

// apps/pi-remote-web/src/features/ask-question/AskQuestionSubmitButton.tsx
export interface AskQuestionSubmitButtonProps {
  readonly disabled: boolean;
}

export function AskQuestionSubmitButton({
  disabled,
}: AskQuestionSubmitButtonProps) {
  return (
    <button
      type="submit"
      className="ask-question-submit"
      disabled={disabled}
    >
      Submit answer
    </button>
  );
}
