// src/mobile-app/src/lib/features/ask-question/AskQuestionPrompt.svelte
<script module lang="ts">
  import type { AskQuestionViewModel } from '../../../features/ask-question/askQuestionTypes.js';

  export interface AskQuestionPromptProps {
    readonly viewModel: AskQuestionViewModel;
  }
</script>

<script lang="ts">
  let { viewModel }: AskQuestionPromptProps = $props();
</script>

<!-- @ds slot: prompt — the question eyebrow + display headline. -->
<div class="ask-question-prompt">
  <!-- @ds slot: kicker — the "Pi asks" eyebrow. -->
  <p class="ask-question-kicker">Pi asks</p>
  <h2>{viewModel.display.prompt}</h2>
</div>

// apps/pi-remote-web/src/features/ask-question/AskQuestionPrompt.tsx
import type { AskQuestionViewModel } from './askQuestionTypes.js';

export function AskQuestionPrompt({ viewModel }: { readonly viewModel: AskQuestionViewModel }) {
  // @ds slot: prompt — the question eyebrow + display headline.
  return (
    <div className="ask-question-prompt">
      {/* @ds slot: kicker — the "Pi asks" eyebrow. */}
      <p className="ask-question-kicker">Pi asks</p>
      <h2>{viewModel.display.prompt}</h2>
    </div>
  );
}
