// app-mobile/src/pages/chat/features/ask-question/ask-question-option-row.svelte
<script module lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // MODULE: ASK QUESTION OPTION ROW
  // ───────────────────────────────────────────────────────────────────

  import type { AskQuestionOption } from '@pi-remote/pi-rpc-protocol';

  export interface AskQuestionOptionRowProps {
    readonly option: AskQuestionOption;
    readonly selected: boolean;
    readonly selectionMode: 'single' | 'multiple';
    readonly disabled: boolean;
    readonly onToggle: (optionId: string) => void;
  }
</script>

<script lang="ts">
  import './ask-question-option-row.css';
  let { option, selected, selectionMode, disabled, onToggle }: AskQuestionOptionRowProps = $props();
</script>

<!-- @ds slot: option-row — one answer option; states idle · hover · pressed · selected · disabled. -->
<button
  type="button"
  class="ask-question-option-row"
  aria-pressed={selected}
  aria-label={option.label}
  {disabled}
  onclick={() => onToggle(option.id)}
>
  <!-- @ds slot: option-indicator — single (circle) / multiple (square) selection glyph. -->
  <span
    class={`ask-question-option-indicator ask-question-option-indicator-${selectionMode}`}
    aria-hidden="true"
  >
    {selected ? '✓' : ''}
  </span>
  <!-- @ds slot: option-copy — the option label + optional description. -->
  <span class="ask-question-option-copy">
    <span class="ask-question-option-label">{option.label}</span>
    {#if option.description !== undefined}
      <span class="ask-question-option-description">{option.description}</span>
    {/if}
  </span>
</button>

<!-- @ds surface: ask-question option-row — one answer option. Decomposed into this co-located CSS file; native
     :hover/:focus-visible/:disabled and the aria-pressed selected state preserved; the dark-theme
     selected re-ink uses :global(:root[data-theme='dark']). Values unchanged. -->

// apps/pi-remote-web/src/features/ask-question/AskQuestionOptionRow.tsx
import type { AskQuestionOption } from '@pi-remote/pi-rpc-protocol';

export interface AskQuestionOptionRowProps {
  readonly option: AskQuestionOption;
  readonly selected: boolean;
  readonly selectionMode: 'single' | 'multiple';
  readonly disabled: boolean;
  readonly onToggle: (optionId: string) => void;
}

export function AskQuestionOptionRow({
  option,
  selected,
  selectionMode,
  disabled,
  onToggle,
}: AskQuestionOptionRowProps) {
  // @ds slot: option-row — one answer option; states idle · hover · pressed · selected · disabled.
  return (
    <button
      type="button"
      className="ask-question-option-row"
      aria-pressed={selected}
      aria-label={option.label}
      disabled={disabled}
      onClick={() => onToggle(option.id)}
    >
      {/* @ds slot: option-indicator — single (circle) / multiple (square) selection glyph. */}
      <span
        className={`ask-question-option-indicator ask-question-option-indicator-${selectionMode}`}
        aria-hidden="true"
      >
        {selected ? '✓' : ''}
      </span>
      {/* @ds slot: option-copy — the option label + optional description. */}
      <span className="ask-question-option-copy">
        <span className="ask-question-option-label">{option.label}</span>
        {option.description !== undefined && (
          <span className="ask-question-option-description">{option.description}</span>
        )}
      </span>
    </button>
  );
}
