// apps/pi-remote-web/src/features/ask-question/AskQuestionOptionList.tsx
import type { AskQuestionViewModel } from './askQuestionTypes.js';
import { AskQuestionOptionRow } from './AskQuestionOptionRow.js';

export interface AskQuestionOptionListProps {
  readonly viewModel: AskQuestionViewModel;
  readonly selectedOptionIds: readonly string[];
  readonly disabled: boolean;
  readonly onToggle: (optionId: string) => void;
}

export function AskQuestionOptionList({
  viewModel,
  selectedOptionIds,
  disabled,
  onToggle,
}: AskQuestionOptionListProps) {
  if (viewModel.display.options.length === 0) return null;
  const selected = new Set(selectedOptionIds);
  const selectionLabel = viewModel.selectionMode === 'single' ? 'Choose one' : 'Choose one or more';
  // @ds slot: options — the choice fieldset; legend + the stacked option-row list.
  return (
    <fieldset className="ask-question-options" disabled={disabled}>
      <legend>{selectionLabel}</legend>
      {/* @ds slot: option-list — the stacked option rows. */}
      <div className="ask-question-option-list">
        {viewModel.display.options.map((option) => (
          <AskQuestionOptionRow
            key={option.id}
            option={option}
            selected={selected.has(option.id)}
            selectionMode={viewModel.selectionMode}
            disabled={disabled}
            onToggle={onToggle}
          />
        ))}
      </div>
    </fieldset>
  );
}

// app-mobile/src/pages/chat/features/ask-question/ask-question-option-list.svelte
<script module lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // MODULE: ASK QUESTION OPTION LIST
  // ───────────────────────────────────────────────────────────────────

  import type { AskQuestionViewModel } from './ask-question-types.js';

  export interface AskQuestionOptionListProps {
    readonly viewModel: AskQuestionViewModel;
    readonly selectedOptionIds: readonly string[];
    readonly disabled: boolean;
    readonly onToggle: (optionId: string) => void;
  }
</script>

<script lang="ts">
  import AskQuestionOptionRow from './ask-question-option-row.svelte';

  import './ask-question-option-list.css';

  let { viewModel, selectedOptionIds, disabled, onToggle }: AskQuestionOptionListProps = $props();

  const selected = $derived(new Set(selectedOptionIds));
  const selectionLabel = $derived(
    viewModel.selectionMode === 'single' ? 'Choose one' : 'Choose one or more',
  );
</script>

{#if viewModel.display.options.length > 0}
  <!-- @ds slot: options — the choice fieldset; legend + the stacked option-row list. -->
  <fieldset class="ask-question-options" {disabled}>
    <legend>{selectionLabel}</legend>
    <!-- @ds slot: option-list — the stacked option rows. -->
    <div class="ask-question-option-list">
      {#each viewModel.display.options as option (option.id)}
        <AskQuestionOptionRow
          {option}
          selected={selected.has(option.id)}
          selectionMode={viewModel.selectionMode}
          {disabled}
          {onToggle}
        />
      {/each}
    </div>
  </fieldset>
{/if}

<!-- @ds surface: ask-question option-list — the choice fieldset + stacked rows (rows are a child component). Decomposed into this co-located CSS file; values unchanged. -->
