// apps/pi-remote-web/src/features/ask-question/AskQuestionPrompt.tsx
import type { AskQuestionViewModel } from './askQuestionTypes.js';

export function AskQuestionPrompt({ viewModel }: { readonly viewModel: AskQuestionViewModel }) {
  // @ds slot: prompt — the question eyebrow + display headline.
  return (
    <div className="ask-question-prompt">
      {/* @ds slot: kicker — the "Pi asks" eyebrow. */}
      <p className="ask-question-kicker">Pi asks</p>
      <h2>{viewModel.display.prompt}</h2>
    </div>
  );
}

// app-mobile/src/pages/chat/features/ask-question/ask-question-prompt.svelte
<script module lang="ts">
  // ───────────────────────────────────────────────────────────────────
  // MODULE: ASK QUESTION PROMPT
  // ───────────────────────────────────────────────────────────────────

  import type { AskQuestionViewModel } from './ask-question-types.js';

  export interface AskQuestionPromptProps {
    readonly viewModel: AskQuestionViewModel;
  }
</script>

<script lang="ts">
  import './ask-question-prompt.css';
  let { viewModel }: AskQuestionPromptProps = $props();
</script>

<!-- @ds slot: prompt — the question eyebrow + display headline. -->
<div class="ask-question-prompt">
  <!-- @ds slot: kicker — the "Pi asks" eyebrow. -->
  <p class="ask-question-kicker">Pi asks</p>
  <h2>{viewModel.display.prompt}</h2>
</div>

<!-- @ds surface: ask-question prompt — eyebrow + display headline. Decomposed into this co-located CSS file; values unchanged. -->
