// app-mobile/src/artifacts/ImagePlaceholder.tsx
import type { CSSProperties } from 'react';

export interface ImagePlaceholderProps {
  readonly aspectRatio?: number | null;
  readonly state: string;
  readonly noAspect?: boolean;
}

export function ImagePlaceholder({ aspectRatio, state, noAspect = false }: ImagePlaceholderProps) {
  const style: CSSProperties =
    !noAspect && aspectRatio !== null && aspectRatio !== undefined
      ? { aspectRatio: String(aspectRatio) }
      : {};
  return (
    <div
      className="inbound-image-well inbound-image-well-placeholder"
      data-image-well="placeholder"
      data-image-state={state}
      data-no-pixels="true"
      style={style}
      aria-hidden="true"
    >
      <span className="inbound-image-placeholder-pattern" />
    </div>
  );
}

// app-mobile/src/pages/chat/artifacts/image-placeholder.svelte
<script lang="ts">
  // @ds surface: ImagePlaceholder — empty inbound-image well shown while pixels are unavailable.
  interface Props {
    aspectRatio?: number | null;
    state: string;
    noAspect?: boolean;
  }

  let { aspectRatio, state, noAspect = false }: Props = $props();
</script>

<div
  class="inbound-image-well inbound-image-well-placeholder"
  data-image-well="placeholder"
  data-image-state={state}
  data-no-pixels="true"
  style:aspect-ratio={!noAspect && aspectRatio !== null && aspectRatio !== undefined
    ? String(aspectRatio)
    : undefined}
  aria-hidden="true"
>
  <span class="inbound-image-placeholder-pattern"></span>
</div>
